global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'currency-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['currency-service:8080']
        labels:
          application: 'currency-converter'
          environment: 'docker'
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']